name: Integration
on:
  push:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  integration:
    name: Integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: kvrhdn/tfe-run@master
        with:
          token: ${{ secrets.TFE_TOKEN }}
          workspace: tfe-run-integration
          speculative: true
          tf-vars: 'run_number = ${{ github.run_number }}'
        id: plan

      - name: Assert speculative plan has changes
        if: steps.plan.outputs.has-changes == 'false'
        run: |
          echo "Expected speculative plan to have changes, but had not"
          exit 1

      - uses: kvrhdn/tfe-run@master
        with:
          token: ${{ secrets.TFE_TOKEN }}
          workspace: tfe-run-integration
          message: "Integration run ${{ github.run_number }}"
          tf-vars: 'run_number = ${{ github.run_number }}'

        # TODO support retrieve terraform outputs from tfe-run to get URL of the bucket
      - name: Assert run number is published to S3
        run: |
          EXPECTED="GitHub Actions run number: ${{ github.run_number }}"
          ACTUAL=$(curl http://tfe-run-integration.s3-website.eu-central-1.amazonaws.com)

          if [ "$EXPECTED" != "$ACTUAL" ]; then
            echo "Data on S3 does not match with expectations!"
            echo ""
            echo "Got:      '$ACTUAL'"
            echo "Expected: '$EXPECTED'"
            exit 1
          fi
